def any_lowercase1(s):
    for c in s:
        if c.islower():
            return True
        else:
            return False

def rotate_word(word,a):
    if word.islower():
        for letter in word:
            b = ord(letter)
            b = b + a
            print(chr(b), end='')
    elif not word.islower():
        for letter in word:
            b = ord(letter)
def make_word_dict():
    d= dict()
    fin = open('words.txt')
    for line in fin:
        word = line.strip()
        d[word] = None
    return d

def rotate_pairs(word, word_dict):
    """Prints all words that can be generated by rotating word.

    word: string
    word_dict: dictionary with words as keys
    """
    for i in range(1, 14):
        rotated = rotate_word(word, i)
        if rotated in word_dict:
            print(word, i, rotated)
word_dict = make_word_dict()
for word in word_dict:
    rotate_pairs(word,word_dict)

